version: '3'

networks:
  classifieds-rest-api-network:
    driver: bridge

services:
  classifieds-rest-api:
    build:
      context: .
      dockerfile: ./cmd/classifieds-rest-api/deploy/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: on-failure
    networks:
      - classifieds-rest-api-network
  db:
    image: postgres:11.1
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    restart: on-failure
    networks:
      - classifieds-rest-api-network